Debugging hab-advection merge

diff --git a/.github/workflows/run_model.yml b/.github/workflows/run_model.yml
--- a/.github/workflows/run_model.yml
+++ b/.github/workflows/run_model.yml
@@ -117,6 +117,9 @@ jobs:
           waves_file=${{ env.DATE_DIR }}/downloaded_data/${{ inputs.WAVES }}/${{ inputs.WAVES }}_${{ inputs.RUN_DATE }}.nc
           flag_file=${{ env.DATE_DIR }}/downloaded_data/PHYTOPLANKTON_FLAGS/PHYTO_${{ inputs.RUN_DATE }}.nc
 
+          echo "--- CHECKING DIRECTORIES ---"
+          ls -la ${{ env.DATE_DIR }}/downloaded_data/${{ inputs.OGCM }}/ || echo "OGCM dir missing"
+          ls -la ${{ env.DATE_DIR }}/downloaded_data/${{ inputs.WIND }}/for_croco/ || echo "WIND dir missing"
 
           for f in "$ogcm_file" "$wind_file_u" "$wind_file_v" "$waves_file" "$flag_file"; do
             if [ ! -f "$f" ]; then
@@ -143,11 +146,21 @@ jobs:
               echo "files_ok=false" >> "$GITHUB_OUTPUT"
             fi
           fi
-     
+
+  debug_variables:
+    needs: [setup_config, check_input_files]
+    runs-on: ${{ inputs.RUNNER_NAME }}
+    steps:
+      - name: Print condition values
+          run: |
+            echo "--- DEBUG OUTPUT ---"
+            echo "inputs.RUN_MODEL value: '${{ inputs.RUN_MODEL }}'"
+            echo "files_ok output value: '${{ needs.check_input_files.outputs.files_ok }}'"
+            echo "--------------------"
+
   run_model:
     needs: [setup_config,check_input_files]
-    # if: ${{ inputs.RUN_MODEL == 'true' && needs.check_input_files.outputs.files_ok == 'true' }}
-    if: (inputs.RUN_MODEL == 'true' || inputs.RUN_MODEL == true) && needs.check_input_files.outputs.files_ok == 'true'
+    if: ${{ inputs.RUN_MODEL == 'true' && needs.check_input_files.outputs.files_ok == 'true' }}
     runs-on: ${{ inputs.RUNNER_NAME }}
     steps:
       - name: run the model
