Testing opendrift HAB-Advection operational workflow.

diff --git a/.github/workflows/sandbox.yml b/.github/workflows/sandbox.yml
--- a/.github/workflows/sandbox.yml
+++ b/.github/workflows/sandbox.yml
@@ -1,10 +1,86 @@
 name: Sandbox for testing individual calleable workflows
-# (not used in th operational workflow at all)
 
 on:
   workflow_dispatch:
 
 jobs:
-  build_image:
-    uses: ./.github/workflows/build_image.yml  # Path to your reusable workflow
- 
+  build_cli:
+    uses: ./.github/workflows/build_images.yml
+    with:
+      IMAGE_ID: cli
+
+
+  # download phytoplankton flags
+  download_phyto:
+    runs-on: mims3
+    needs: [build_cli]
+    steps:
+      - name: Clean and create CSIR PHYTOPLANKTON FLAGS directory with correct permissions
+        run: |
+          sudo rm -rf /home/somisana/ops/HAB-Advection/20260429_00/downloaded_data/PHYTOPLANKTON_FLAGS
+          sudo mkdir -p /home/somisana/ops/HAB-Advection/20260429_00/downloaded_data/PHYTOPLANKTON_FLAGS
+          sudo chown -R $(id -u):$(id -g) /home/somisana/ops/HAB-Advection/20260429_00/downloaded_data/PHYTOPLANKTON_FLAGS
+          sudo chmod -R 775 /home/somisana/ops/HAB-Advection/20260429_00/downloaded_data/PHYTOPLANKTON_FLAGS
+
+      - name: Download PHYTO
+        uses: nick-fields/retry@master
+        with:
+          timeout_minutes: 60
+          retry_wait_seconds: 300
+          max_attempts: 3
+          retry_on: any
+          warning_on_retry: true
+          shell: bash
+          continue_on_error: false
+          command: |
+            docker run \
+              --user $(id -u):$(id -g) \
+              --rm \
+              --entrypoint bash \
+              -v /home/somisana/ops/HAB-Advection/20260429_00/downloaded_data/PHYTOPLANKTON_FLAGS:/tmp \
+              ghcr.io/saeon/somisana-download_download-phyto-flags:latest \
+              -c 'python cli.py download_phytoplankton_flags \
+                --date "2026-04-28 00:00:00" \
+                --dir_out "/tmp" && echo "Download completed" || echo "Download failed"'
+                
+  # Download wavs
+  download_waves:
+    runs-on: mims3
+    needs: [build_cli,download_phyto]
+    steps:
+      - name: Clean and create CMEMS WAVES directory with correct permissions
+        run: |
+          sudo rm -rf /home/somisana/ops/HAB-Advection/20260429_00/downloaded_data/CMEMS_WAVES
+          sudo mkdir -p /home/somisana/ops/HAB-Advection/20260429_00/downloaded_data/CMEMS_WAVES
+          sudo chown -R $(id -u):$(id -g) /home/somisana/ops/HAB-Advection/20260429_00/downloaded_data/CMEMS_WAVES
+          sudo chmod -R 775 /home/somisana/ops/HAB-Advection/20260429_00/downloaded_data/CMEMS_WAVES
+
+      - name: Download WAVES
+        uses: nick-fields/retry@master
+        with:
+          timeout_minutes: 60
+          retry_wait_seconds: 300
+          max_attempts: 3
+          retry_on: any
+          warning_on_retry: true
+          shell: bash
+          continue_on_error: false
+          command: |
+            docker run \
+              --user $(id -u):$(id -g) \
+              --rm \
+              --entrypoint bash \
+              -v /home/somisana/ops/HAB-Advection/20260429_00/downloaded_data/CMEMS_WAVES:/tmp \
+              ghcr.io/saeon/somisana-download_download-phyto-flags:latest \
+              -c 'python cli.py download_cmems_ops \
+                --usrname grautenbach \
+                --passwd ZuluTheMoo2021! \
+                --dataset cmems_mod_glo_wav_anfc_0.083deg_PT3H-i \
+                --varList "VHM0,VHM0_SW1,VHM0_SW2,VHM0_WW,VMDR,VMDR_SW1,VMDR_SW2,VMDR_WW,VPED,VSDX,VSDY,VTM01_SW1,VTM01_SW2,VTM01_WW,VTM02,VTM10,VTPK"  \
+                --domain 11,36,-39,-25 \
+                --depths 0,0 \
+                --run_date "2026-04-29 00:00:00" \
+                --hdays 5 \
+                --fdays 5 \
+                --outputDir "/tmp" \ 
+                --outputFile "waves_20260429.nc" && echo "Download completed" || echo "Download failed"' 
